version: "3"
services:
  nginx:
    image: nginx:${NGINX_VERSION}
    ports:
      - "${NGINX_HTTP_HOST_PORT}:80"
      - "${NGINX_HTTPS_HOST_PORT}:443"
    volumes:
      - ${SOURCE_DIR}:/var/www/html/:rw
      - ${NGINX_CONFD_DIR}:/etc/nginx/conf.d/:rw
      - ${NGINX_CONF_FILE}:/etc/nginx/nginx.conf:ro
      - ${NGINX_LOG_DIR}:/var/log/nginx/:rw
    restart: always
    networks:
      - default

  php70:
    build:
      context: .
      args:
        PHP_VERSION: ${PHP70_VERSION}
        PHP_XDEBUG: ${PHP70_XDEBUG}
        PHP_SWOOLE: ${PHP70_SWOOLE}
        PHP_REDIS: ${PHP70_REDIS}
        PHP_MONGO: ${PHP70_MONGO}
        REPLACE_SOURCE_LIST: ${REPLACE_SOURCE_LIST}
    ports:
      - "${PHP_SWOOLE_HOST_PORT}:9505"
    volumes:
      - ${SOURCE_DIR}:/var/www/html/:rw
      - ${PHP70_PHP_CONF_FILE}:/usr/local/etc/php/php.ini:ro
      - ${PHP70_FPM_CONF_FILE}:/usr/local/etc/php-fpm.d/www.conf:rw
      - ${PHP70_LOG_DIR}:/mnt/:rw
    restart: always
    cap_add:
      - SYS_PTRACE
    networks:
      - default


  mysql:
    image: mysql:${MYSQL_VERSION}
    ports:
      - "${MYSQL_HOST_PORT}:3306"
    volumes:
      - ${MYSQL_CONF_FILE}:/etc/mysql/conf.d/mysql.cnf:ro
      - ${MYSQL_DATA_DIR}:/var/lib/mysql/:rw
    restart: always
    networks:
      - default
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
#      MYSQL_DATABASE: symfony
#      MYSQL_USER: symfony
#      MYSQL_PASSWORD: symfony

  redis:
    image: redis:${REDIS_VERSION}
    ports:
      - "${REDIS_HOST_PORT}:6379"
    volumes:
      - ${REDIS_CONF_FILE}:/etc/redis.conf:ro
      - ${REDIS_DATA_DIR}:/data/:rw
    restart: always
    entrypoint: ["redis-server", "/etc/redis.conf"]
    networks:
      - default
    
  mongo:
    image: mongo:${MONGO_VERSION}
    ports:
      - "${MONGO_HOST_PORT}:27017"
    volumes:
#      - ${MONGO_CONF_FILE}:/etc/mongo/mongod.conf:ro
      - ${MONGO_DATA_DIR}:/data/db/:rw
    restart: always
    networks:
      - default
    environment:
      MONGO_INITDB_ROOT_USERNAME: "${MONGO_ROOT_USERNAME}"
      MONGO_INITDB_ROOT_PASSWORD: "${MONGO_ROOT_PASSWORD}"


networks:
  default:
