_wdt:
    resource: "@WebProfilerBundle/Resources/config/routing/wdt.xml"
    prefix:   /_wdt

_profiler:
    resource: "@WebProfilerBundle/Resources/config/routing/profiler.xml"
    prefix:   /_profiler

_main:
    resource: routing.yml
# AcmeDemoBundle routes (to be removed)
clean_api:
    resource: "@CleanAPIBundle/Resources/config/routing.yml"
    prefix:   /

clean_admin:
    resource: "@CleanAdminBundle/Resources/config/routing.yml"
    prefix:   /
